apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: k8s-app
spec:
  replicas: 3
  serviceName: headless-mysql-svc
  selector:
    matchLabels:
      app: k8s-mysql
  template:
    metadata:
      labels:
        app: k8s-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: k8s-mysql
          image: mysql:5.7
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
               secretKeyRef: 
                key: ROOT_PASSWORD
                name: mysql-secret
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE     
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi